# Generated by Django 5.0.6 on 2024-06-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0003_alter_women_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="women.category"),
        ),
    ]
