# Generated by Django 5.0.6 on 2024-06-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0007_husband_women_husband"),
    ]

    operations = [
        migrations.AddField(
            model_name="husband",
            name="m_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
