# Generated by Django 5.0.6 on 2024-06-14 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0008_husband_m_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="women",
            options={"ordering": ["-time_create"], "verbose_name": "Woman", "verbose_name_plural": "Women"},
        ),
        migrations.AlterField(
            model_name="women",
            name="slug",
            field=models.SlugField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(5, message="Minimum 5 symbols"),
                    django.core.validators.MaxLengthValidator(100, "Maximum 100 symbols"),
                ],
            ),
        ),
    ]
